# Generated by Django 5.0.6 on 2024-07-29 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_amount_alter_userexpense_amount_owed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpense',
            name='percentage_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
