# Generated by Django 5.0.6 on 2024-07-28 13:26

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[user.validators.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
