# Generated by Django 5.0.6 on 2024-07-28 13:37

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_mobile_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[user.validators.validate_mobile]),
        ),
    ]
